const AmericaCity=[
    "Massachusetts",
    "Washington",
    "California",
    "Oregon",
    "Wisconsin",
    "Maine",
    "Michigan",
    "Nevada",
    "New Mexico",
    "Colorado",
    "Wyoming",
    "Kansas",
    "Nebraska",
    "Oklahoma",
    "Missouri",
    "Illinois",
    "Indiana",
    "Vermont",
    "Arkansas",
    "Texas",
    "Rhode Island",
    "Alabama",
    "Mississippi",
    "North Carolina",
    "Virginia",
    "Iowa",
    "Maryland",
    "Delaware",
    "Pennsylvania",
    "New Jersey",
    "New York",
    "Idaho",
    "South Dakota",
    "Connecticut",
    "New Hampshire",
    "Kentucky",
    "Ohio",
    "Tennessee",
    "West Virginia",
    "District of Columbia",
    "Louisiana",
    "Florida",
    "Georgia",
    "South Carolina",
    "Minnesota",
    "Montana",
    "North Dakota",
    "Arizona",
    "Utah",
    "Hawaii",
    "Alaska",
]