const AmericaCity=[
    "Massachusetts",
    "Washington",
    "California",
    "Oregon",
    "Wisconsin",
    "Maine",
    "Michigan",
    "Nevada",
    "New Mexico",
    "Colorado",
    "Wyoming",
    "Kansas",
    "Nebraska",
    "Oklahoma",
    "Missouri",
    "Illinois",
    "Indiana",
    "Vermont",
    "Arkansas",
    "Texas",
    "Rhode Island",
    "Alabama",
    "Mississippi",
    "North Carolina",
    "Virginia",
    "Iowa",
    "Maryland",
    "Delaware",
    "Pennsylvania",
    "New Jersey",
    "New York",
    "Idaho",
    "South Dakota",
    "Connecticut",
    "New Hampshire",
    "Kentucky",
    "Ohio",
    "Tennessee",
    "West Virginia",
    "District of Columbia",
    "Louisiana",
    "Florida",
    "Georgia",
    "South Carolina",
    "Minnesota",
    "Montana",
    "North Dakota",
    "Arizona",
    "Utah",
    "Hawaii",
    "Alaska",
]


const AsiaCountry=[
    "Iran",
    "Philippines",
    "Saudi Arabia",
    "Japan",
    "Thailand",
    "Oman",
    "Yemen",
    "India",
    "South Korea",
    "Bangladesh",
    "Spratly Islands",
    "China",
    "Bahrain",
    "Myanmar",
    "Indonesia",
    "Singapore",
    "Russia",
    "Scarborough Reef",
    "Malaysia",
    "Azerbaijan",
    "Armenia",
    "Vietnam",
    "Tajikistan",
    "Uzbekistan",
    "East Timor",
    "Cambodia",
    "Bhutan",
    "Georgia",
    "Kazakhstan",
    "Israel",
    "Syria",
    "Jordan",
    "Turkmenistan",
    "Cyprus No Mans Area",
    "Mongolia",
    "Kuwait",
    "Iraq",
    "United Arab Emirates",
    "Laos",
    "Pakistan",
    "Siachen Glacier",
    "Qatar",
    "Turkey",
    "Brunei",
    "Afghanistan",
    "North Korea",
    "Lebanon",
    "Northern Cyprus",
    "Cyprus",
    "Taiwan",
    "Nepal",
    "Sri Lanka",
    "Kyrgyzstan"
]