const AmericaCity=[
    "Massachusetts",
    "Washington",
    "California",
    "Oregon",
    "Wisconsin",
    "Maine",
    "Michigan",
    "Nevada",
    "New Mexico",
    "Colorado",
    "Wyoming",
    "Kansas",
    "Nebraska",
    "Oklahoma",
    "Missouri",
    "Illinois",
    "Indiana",
    "Vermont",
    "Arkansas",
    "Texas",
    "Rhode Island",
    "Alabama",
    "Mississippi",
    "North Carolina",
    "Virginia",
    "Iowa",
    "Maryland",
    "Delaware",
    "Pennsylvania",
    "New Jersey",
    "New York",
    "Idaho",
    "South Dakota",
    "Connecticut",
    "New Hampshire",
    "Kentucky",
    "Ohio",
    "Tennessee",
    "West Virginia",
    "District of Columbia",
    "Louisiana",
    "Florida",
    "Georgia",
    "South Carolina",
    "Minnesota",
    "Montana",
    "North Dakota",
    "Arizona",
    "Utah",
    "Hawaii",
    "Alaska",
]


const AsiaCountry=[
    "Iran",
    "Philippines",
    "Saudi Arabia",
    "Japan",
    "Thailand",
    "Oman",
    "Yemen",
    "India",
    "South Korea",
    "Bangladesh",
    "Spratly Islands",
    "China",
    "Bahrain",
    "Myanmar",
    "Indonesia",
    "Singapore",
    "Russia",
    "Scarborough Reef",
    "Malaysia",
    "Azerbaijan",
    "Armenia",
    "Vietnam",
    "Tajikistan",
    "Uzbekistan",
    "East Timor",
    "Cambodia",
    "Bhutan",
    "Georgia",
    "Kazakhstan",
    "Israel",
    "Syria",
    "Jordan",
    "Turkmenistan",
    "Cyprus No Mans Area",
    "Mongolia",
    "Kuwait",
    "Iraq",
    "United Arab Emirates",
    "Laos",
    "Pakistan",
    "Siachen Glacier",
    "Qatar",
    "Turkey",
    "Brunei",
    "Afghanistan",
    "North Korea",
    "Lebanon",
    "Northern Cyprus",
    "Cyprus",
    "Taiwan",
    "Nepal",
    "Sri Lanka",
    "Kyrgyzstan"
]




const world=[
    "Greenland",
    "Scarborough Reef",
    "Bajo Nuevo Bank (Petrel Is.)",
    "Sri Lanka",
    "American Samoa",
    "Denmark",
    "Faroe Islands",
    "Guam",
    "Northern Mariana Islands",
    "Puerto Rico",
    "United States Minor Outlying Islands",
    "United States of America",
    "United States Virgin Islands",
    "Canada",
    "Sao Tome and Principe",
    "Japan",
    "Cape Verde",
    "Dominica",
    "Seychelles",
    "Jamaica",
    "Samoa",
    "Oman",
    "Saint Vincent and the Grenadines",
    "Solomon Islands",
    "Saint Lucia",
    "France",
    "Nauru",
    "Norway",
    "Federated States of Micronesia",
    "Saint Kitts and Nevis",
    "China",
    "Bahrain",
    "Tonga",
    "Indonesia",
    "Mauritius",
    "Trinidad and Tobago",
    "Serranilla Bank",
    "The Bahamas",
    "Palau",
    "Tuvalu",
    "Marshall Islands",
    "Chile",
    "Kiribati",
    "Philippines",
    "Thailand",
    "Grenada",
    "Antigua and Barbuda",
    "Spain",
    "Barbados",
    "Italy",
    "Malta",
    "Maldives",
    "Spratly Islands",
    "Papua New Guinea",
    "Singapore",
    "Cyprus No Mans Area",
    "United Kingdom",
    "Cyprus",
    "Greece",
    "Comoros",
    "Fiji",
    "Russia",
    "Vatican",
    "San Marino",
    "Azerbaijan",
    "Lesotho",
    "Tajikistan",
    "Mali",
    "Algeria",
    "Taiwan",
    "Kazakhstan",
    "Kyrgyzstan",
    "Uzbekistan",
    "United Republic of Tanzania",
    "Argentina",
    "Saudi Arabia",
    "Netherlands",
    "Yemen",
    "United Arab Emirates",
    "India",
    "Turkey",
    "Bangladesh",
    "Switzerland",
    "Suriname",
    "Portugal",
    "Malaysia",
    "Cambodia",
    "Vietnam",
    "Brazil",
    "Panama",
    "Nigeria",
    "Iran",
    "Haiti",
    "Dominican Republic",
    "Sierra Leone",
    "Guinea Bissau",
    "Bosnia and Herzegovina",
    "Croatia",
    "Estonia",
    "Mexico",
    "Tunisia",
    "Kuwait",
    "Germany",
    "Myanmar",
    "Equatorial Guinea",
    "Gabon",
    "Ireland",
    "Poland",
    "Lithuania",
    "Egypt",
    "Uganda",
    "Democratic Republic of the Congo",
    "Armenia",
    "Macedonia",
    "Albania",
    "Cameroon",
    "Benin",
    "Northern Cyprus",
    "Georgia",
    "East Timor",
    "Turkmenistan",
    "Peru",
    "Malawi",
    "Mongolia",
    "Angola",
    "Mozambique",
    "South Africa",
    "Costa Rica",
    "El Salvador",
    "Belize",
    "Colombia",
    "Ecuador",
    "Libya",
    "Sudan",
    "North Korea",
    "South Korea",
    "Guyana",
    "Honduras",
    "Nicaragua",
    "Ethiopia",
    "Somalia",
    "Ghana",
    "Slovenia",
    "Guatemala",
    "Jordan",
    "West Bank",
    "Israel",
    "Zambia",
    "Monaco",
    "Uruguay",
    "Rwanda",
    "Bolivia",
    "Republic of Congo",
    "Western Sahara",
    "Republic of Serbia",
    "Montenegro",
    "Togo",
    "Laos",
    "Afghanistan",
    "Siachen Glacier",
    "Pakistan",
    "Bulgaria",
    "Ukraine",
    "Romania",
    "Qatar",
    "Liechtenstein",
    "Austria",
    "Swaziland",
    "Hungary",
    "Niger",
    "Luxembourg",
    "Andorra",
    "Ivory Coast",
    "Liberia",
    "Brunei",
    "Mauritania",
    "Belgium",
    "Iraq",
    "Gambia",
    "Morocco",
    "Chad",
    "Kosovo",
    "Lebanon",
    "Somaliland",
    "Djibouti",
    "Eritrea",
    "Burundi",
    "Senegal",
    "Guinea",
    "Zimbabwe",
    "Paraguay",
    "Belarus",
    "Latvia",
    "Syria",
    "Namibia",
    "Burkina Faso",
    "South Sudan",
    "Central African Republic",
    "Moldova",
    "Gaza Strip",
    "Kenya",
    "Czech Republic",
    "Slovakia",
    "Vanuatu",
    "New Zealand",
    "Cuba",
    "Finland",
    "Sweden",
    "Australia",
    "Madagascar",
    "Venezuela",
    "Iceland",
    "Botswana",
    "Bhutan",
    "Nepal"
]